#version: "3"

services:
  ai-chat-db:
    container_name: ai-chat-db
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mariadb:10.8.2
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/db-vol:/var/lib/mysql
      - ./data/sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: aa123456
      MYSQL_USER: ai_chat_user
      MYSQL_PASSWORD: ai_chat_user@123
      MYSQL_DATABASE: aichat
      MYSQL_BACKUP_PASSWORD: ai_chat_user@123
      MYSQL_BACKUP_USER: backup_user
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION
      --lower_case_table_names=2
      --max_connections=1000
    networks:
      - ai-network
  ai-chat-redis:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:7.2.5
    container_name: ai-chat-redis
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "6379:6379"
    networks:
      - ai-network
  ai-chat-mongodb:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/mongo:7.0.12
    container_name: ai-chat-mongodb
    privileged: true
    restart: always
    ports:
      - 27017:27017 #  端口
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - ./data/mongodb/data:/data/db               #映射当前目录下的data目录至容器内/data目录
    networks:
      - ai-network
  ai-chat-backend:
    #需要修改镜像名称
    container_name: ai-chat-backend
    build:
      context: ../ai-chat-backend
    image: yzt/ai-chat-backend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:8080
    depends_on:
      - ai-chat-db
      - ai-chat-redis
      - ai-chat-mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-network
  front:
    #需要修改镜像名称
    container_name: ai-chat-web
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../ai-chat-web/config/nginx.conf:/etc/nginx/nginx.conf:rw
      - ../ai-chat-web/config/my_server_block.conf:/etc/nginx/conf.d/my_server_block.conf:rw
      - ../ai-chat-web/dist:/app
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 5173:5173
    depends_on:
      - ai-chat-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
